
appname: apache
replicaCount: 10
image:
  repository: docker.io/bitnami/apache
  tag: 2.4.41-debian-10-r29
  pullPolicy: IfNotPresent

enterprise:
  name: appsapp
namespace:
 name: default

service:
  type: NodePort
  port: 8080
  targetport: 8080
  nodeport: 31228
  servicename: httpd-service

pvc:
  accessmodes: ReadWriteOnce
  request: 1Gi
  claimname: myhttpdclaim

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      path: /webserver
  tls: []

resources: 
  limits:
    cpu: 400m
    memory: 360Mi
  requests:
    cpu: 250m
    memory: 148Mi

serviceAccount:
  create: false

nodeSelector: {}

tolerations: []

affinity: {}
